//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigTransformerCore.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigTransformerCore.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;NorthwindConnectionString&quot; connectionString=&quot;Data Source=JODAVIS-DEV1;Initial Catalog=Northwind;Integrated Security=True&quot; providerName=&quot;System.Data.SqlClient&quot; /&gt;
        ///  &lt;/connectionStrings&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        public static string WarningsAndErrors_source {
            get {
                return ResourceManager.GetString("WarningsAndErrors_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration xmlns:xct=&quot;http://schemas.microsoft.com/XML-Document-Transform&quot;&gt;
        ///  &lt;connectionStrings&gt;
        ///    &lt;!-- BadTypeName --&gt;
        ///    &lt;add xct:Transform=&quot;Foo&quot;/&gt;
        ///    &lt;add xct:Transform=&quot;Match&quot;/&gt;
        ///
        ///    &lt;!-- NoValidConstructor --&gt;
        ///    &lt;add xct:Transform=&quot;NoValidConstructor&quot;/&gt;
        ///
        ///    &lt;!-- BadArgumentValue --&gt;
        ///    &lt;add foo=&quot;foo&quot; xct:Transform=&quot;SetAttributes:foo&quot;/&gt;
        ///    &lt;add foo=&quot;foo&quot; xct:Transform=&quot;SetAttributes(foo&quot;/&gt;
        ///    &lt;add foo=&quot;foo&quot; xct:Transform=&quot;#SetAttributes#&quot;/&gt;
        ///
        ///    &lt;!-- I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WarningsAndErrors_transform {
            get {
                return ResourceManager.GetString("WarningsAndErrors_transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///    &lt;appSettings /&gt;
        ///    &lt;connectionStrings /&gt;
        ///    &lt;system.web&gt;
        ///        &lt;compilation debug=&quot;true&quot;&gt;
        ///
        ///        &lt;/compilation&gt;
        ///        &lt;!--
        ///            The &lt;authentication&gt; section enables configuration 
        ///            of the security authentication mode used by 
        ///            ASP.NET to identify an incoming user. 
        ///        --&gt;
        ///        &lt;authentication mode=&quot;Windows&quot; /&gt;
        ///        &lt;!--
        ///            The &lt;customErrors&gt; section enables configuration 
        ///            of what  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///    &lt;appSettings /&gt;
        ///    &lt;connectionStrings /&gt;
        ///    &lt;system.web&gt;
        ///        &lt;compilation&gt;
        ///
        ///        &lt;/compilation&gt;
        ///        &lt;!--
        ///            The &lt;authentication&gt; section enables configuration 
        ///            of the security authentication mode used by 
        ///            ASP.NET to identify an incoming user. 
        ///        --&gt;
        ///        &lt;authentication mode=&quot;Windows&quot; /&gt;
        ///        &lt;!--
        ///            The &lt;customErrors&gt; section enables configuration 
        ///            of what to do if/when [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Web_final {
            get {
                return ResourceManager.GetString("Web_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;!-- For more information on using web.config transformation visit http://go.microsoft.com/fwlink/?LinkId=125889 --&gt;
        ///
        ///&lt;configuration xmlns:xdt=&quot;http://schemas.microsoft.com/XML-Document-Transform&quot;&gt;
        ///  &lt;!--
        ///    In the example below, the &quot;SetAttributes&quot; transform will change the value of 
        ///    &quot;connectionString&quot; to use &quot;ReleaseSQLServer&quot; only when the &quot;Match&quot; locator 
        ///    finds an attribute &quot;name&quot; that has a value of &quot;MyDB&quot;.
        ///    
        ///    &lt;connectionStrings&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Web_Release {
            get {
                return ResourceManager.GetString("Web_Release", resourceCulture);
            }
        }
    }
}
